// Regression test: ALL particles must generate 12 shadow triangles per particle.
// Catches the backface cull bug (2026-04) where front-facing triangles were removed,
// halving the shadow triangle count and killing shadows for thin particles.
//
// See docs/SHADOW_SYSTEM.md for full context.

#include "../src/test_context.h"
#include "../src/particle.h"
#include "../src/core/engine.h"
#include "logosphere/worldgen/humanoid_generator.h"
#include <cstdio>
#include <cassert>

bool test_small_particle_shadow(TestContext& ctx) {
    printf("\n=== Shadow triangle count regression test ===\n");

    ctx.clear_particles();

    // Light
    ctx.add_light_particle(2, 0, 10, 0.1f, 1.0f, 1.0f, 1.0f, 500000.0f, 100.0f);

    // Floor (HEAVY_STATIC)
    {
        Particle f = {};
        f.shape = ParticleShape::BOX;
        f.x = 0; f.y = 0; f.z = 0.05f;
        f.width = 20; f.height = 20; f.thickness = 0.1f;
        f.r = 0.4f; f.g = 0.5f; f.b = 0.3f; f.a = 1.0f;
        f.SetMaterial(Materials::Type::HEAVY_STATIC);
        ctx.add_test_particle(f);
    }

    // Test particles at various sizes
    float sizes[] = {2.0f, 1.0f, 0.5f, 0.25f, 0.1f, 0.05f};
    int num_sizes = 6;
    for (int i = 0; i < num_sizes; i++) {
        Particle p = {};
        p.shape = ParticleShape::BOX;
        p.x = -5.0f + i * 2.0f;
        p.y = 0;
        p.width = sizes[i];
        p.height = sizes[i];
        p.thickness = sizes[i] * 2.0f;
        // Rest each caster ON the floor slab (top at z=0.1). The old fixed
        // z=1.0 sank the 4 m-tall one a full metre below the turtle.
        p.z = 0.1f + p.thickness * 0.5f;
        p.r = 1.0f; p.g = 0.0f; p.b = 0.0f; p.a = 1.0f;
        p.SetMaterial(Materials::Type::STONE);
        ctx.add_test_particle(p);
    }

    // Eva humanoid (29 particles, 0.04-0.25m each)
    auto& engine = ctx.get_engine();
    auto& humanoid_gen = engine.get_worldgen_system().get_humanoid_generator();
    PhysicsHumanoidResult eva = humanoid_gen.generate_humanoid_physics(
        8.0f, 0.0f, 0.5f, -1, HumanoidSpec::eva(), false);

    printf("Scene: 1 floor + 6 cubes (2.0-0.05m) + Eva (%zu particles)\n",
        eva.body_ids.size());

    // Render to trigger shadow triangle generation
    ctx.render();
    ctx.render();
    ctx.render();

    // Count particles and expected shadow triangles
    int particle_count = engine.get_particle_system().count();
    int light_count = 0;
    {
        auto particles = engine.get_particle_system().lock_particles_for_read();
        for (int i = 0; i < particle_count; i++) {
            if (particles[i].is_light_source) light_count++;
        }
    }

    int shadow_generating_particles = particle_count - light_count;
    int expected_shadow_tris = shadow_generating_particles * 12;

    printf("Particles: %d total, %d lights, %d shadow-generating\n",
        particle_count, light_count, shadow_generating_particles);
    printf("Expected shadow triangles: %d (= %d particles × 12 faces)\n",
        expected_shadow_tris, shadow_generating_particles);

    // Verify: count actual shadow triangles generated by the render pipeline
    // We check this by examining the shadow triangle arrays
    // The render pipeline logs shadow count in FRAME_SUBMIT

    // For the headless path, we verify that GetShadowTriangles produces 12 per particle
    int total_shadow_tris = 0;
    {
        auto particles = engine.get_particle_system().lock_particles_for_read();
        std::vector<float> temp;
        for (int i = 0; i < particle_count; i++) {
            if (particles[i].is_light_source) continue;
            if (particles[i].a < 1.0f) continue;
            temp.clear();
            particles[i].GetShadowTriangles(temp);
            int tris = temp.size() / 9;
            total_shadow_tris += tris;

            if (tris != 12) {
                printf("  PROBLEM: particle[%d] generated %d shadow tris (expected 12)\n", i, tris);
                printf("    size=(%.3f,%.3f,%.3f) owner=%d material=%d\n",
                    particles[i].width, particles[i].height, particles[i].thickness,
                    (int)particles[i].owner, (int)particles[i].material_type);
            }
        }
    }

    printf("Actual shadow triangles generated: %d\n", total_shadow_tris);

    // THE KEY ASSERTION: every non-light particle must produce exactly 12 shadow triangles
    bool all_12 = (total_shadow_tris == expected_shadow_tris);
    printf("All particles produce 12 triangles: %s\n", all_12 ? "YES" : "NO");

    if (!all_12) {
        printf("FAIL: Shadow triangle count mismatch!\n");
        printf("  Expected: %d\n", expected_shadow_tris);
        printf("  Actual:   %d\n", total_shadow_tris);
        printf("  If actual is exactly half of expected, backface culling is active.\n");
        printf("  See docs/SHADOW_SYSTEM.md — backface cull must NOT be applied to shadow triangles.\n");
    }

    // Also verify Eva's particles specifically
    int eva_tris = 0;
    {
        auto particles = engine.get_particle_system().lock_particles_for_read();
        std::vector<float> temp;
        for (int pid : eva.body_ids) {
            temp.clear();
            particles[pid].GetShadowTriangles(temp);
            eva_tris += temp.size() / 9;
        }
    }

    int expected_eva_tris = eva.body_ids.size() * 12;
    printf("Eva shadow triangles: %d (expected %d)\n", eva_tris, expected_eva_tris);

    bool eva_ok = (eva_tris == expected_eva_tris);
    if (!eva_ok) {
        printf("FAIL: Eva shadow triangle count wrong! Her shadow will be broken.\n");
    }

    bool pass = all_12 && eva_ok;
    printf("\n%s: shadow triangle regression test\n", pass ? "PASS" : "FAIL");
    return pass;
}
