#ifndef CONTACT_MANIFOLD_H
#define CONTACT_MANIFOLD_H

// ============================================================================
// CONTACT MANIFOLD
// ============================================================================
// Result of narrow-phase collision detection between two particles.
// Contains 1-4 contact points with world positions, penetration depths,
// and a shared contact normal.
//
// Generated by SAT (axis selection) + Sutherland-Hodgman (face clipping).
// Consumed by the sequential impulse solver to create one Constraint
// per contact point.
// ============================================================================

#include <cstddef>

struct ContactPoint {
    float px, py, pz;    // World-space position on reference face
    float penetration;   // Depth behind reference face (positive = inside)
    int point_id;        // Stable identifier for warm-starting (0-3)
};

struct ContactManifold {
    size_t body_a, body_b;
    float normal_x, normal_y, normal_z;  // Unit normal, from A toward B
    int num_points;                       // 0 = no contact, 1-4 = valid
    ContactPoint points[4];              // Fixed-size, no heap allocation
    bool is_face_contact;                // true = face-face, false = edge
    int reference_axis;                  // 0=X, 1=Y, 2=Z
    int reference_body;                  // 0=body_a face, 1=body_b face
};

#endif // CONTACT_MANIFOLD_H
